SET search_path TO projeto_bd;

-- REMOVENDO TABELAS COM CHAVE ESTRANGEIRA (FK)
DROP TABLE IF EXISTS Logistica_Transporte CASCADE;
DROP TABLE IF EXISTS Coleta CASCADE;
DROP TABLE IF EXISTS Ponto_de_Coleta CASCADE;
DROP TABLE IF EXISTS Equipe_Participa_Partida CASCADE;
DROP TABLE IF EXISTS Partida CASCADE;
DROP TABLE IF EXISTS Aluno_Equipe CASCADE;
DROP TABLE IF EXISTS Equipe CASCADE;
DROP TABLE IF EXISTS Tutor CASCADE;
DROP TABLE IF EXISTS Aluno CASCADE;
DROP TABLE IF EXISTS Patrocinadores_Torneio CASCADE;

-- REMOVENDO TABELAS SEM CHAVE ESTRANGEIRA (FK)
DROP TABLE IF EXISTS Centro_de_Reciclagem CASCADE;
DROP TABLE IF EXISTS Transportadora CASCADE;
DROP TABLE IF EXISTS Lixo CASCADE;
DROP TABLE IF EXISTS Escola CASCADE;
DROP TABLE IF EXISTS Torneio CASCADE;

-- REMOVENDO DOMÍNIOS
DROP DOMAIN IF EXISTS SIGLA_ALFA_3 CASCADE;